### ISSUE TITLE
Update the code to reflect the recent TLS 1.2 requirement?

### ISSUE THREAD

**Issue by sjustesen** [paypal/Checkout-NET-SDK#13]
I got this error while trying to get an access token:
The request was aborted: Could not create SSL/TLS secure channel.

Seems it is because either .NET or my server did not default to TLS1.2, which is now a requirement when connecting to the Paypal REST API. Maybe the code should reflect this?

Possible fix.. Insert:
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; into the fetchAccessToken method in /PaypalCheckoutSdk/Core/PaypalHttpClient.cs

**Comment by rajarampadmanathan** [comment]
Will look into this and get back to you

**Comment by sjustesen** [comment]
using .NET Framework 4.7.2 w/IIS Express bundled with VS2017 Community Editon
It happened on a fresh install of the Checkout SDK

**Comment by 90kay** [comment]
Hi @sjustesen Thanks for reporting the issue and providing details.

- https://www.paypal.com/au/webapps/mpp/tls-http-upgrade
TLS 1.2 become mandatory for all external connections to PayPal since 2018. And you can also find it as a prerequisite in the README. 

- The fix you proposed will specify the Security Protocol we use to TLS 1.2 which means we will not supporting any newer version in the future. 

Thanks and please let us know if you have any questions.
